### ISSUE TITLE
Expansions are duplicated when you're in a directory on CD_PATH

### ISSUE THREAD

**Issue by nickcox** [nickcox/cd-extras#11]

**Comment by czhang03** [comment]
Add the pipline `Sort-Object | Get-Unique` in the end of this line: https://github.com/nickcox/cd-extras/blob/957b9a7859a8abad18b9823eb96b1526481bafce/cd-extras/private/ArgumentCompleter.ps1#L11

Probably will work.

Reference: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-unique?view=powershell-6

**Comment by nickcox** [comment]
Thanks for that. Published with [0.4.0](https://www.powershellgallery.com/packages/cd-extras/0.4.0).
