### ISSUE TITLE
cd to invalid subfolder moved to root of drive

### ISSUE THREAD

**Issue by SteveLowe** [nickcox/cd-extras#17]
After installing this module (v0.8.1), cd to a non-existant dir moves to the root of the current drive, with no warning or error
```
PS C:\Users\username\Documents> cd not_a_dir
PS C:\>
```
I would expect it to stay in the current directory and report an error (as vanilla powershell does)
```
PS C:\Users\username\Documents> cd not_a_dir
cd : Cannot find path 'C:\Users\username\Documents\not_a_dir' because it does not exist.
At line:1 char:1
+ cd not_a_dir
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\username\Documents\not_a_dir:String) [Set-Location], Ite
   mNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
PS C:\Users\username\Documents>
```

**Comment by nickcox** [comment]
Thanks, Steve. I think I broke something there. Could you have a go with [0.8.2](https://www.powershellgallery.com/packages/cd-extras/0.8.2)?

**Comment by SteveLowe** [comment]
Have tested 0.8.2, and is fine now.

Thanks for the quick response!
