### ISSUE TITLE
Support for using Get-ChildItemColor Module when using auto completion

### ISSUE THREAD

**Issue by jetersen** [nickcox/cd-extras#19]
Possible to have colored items? Is it already supported or can it be added?
https://github.com/joonro/Get-ChildItemColor

**Comment by nickcox** [comment]
I can't think of a reason why this wouldn't work. (Although I haven't tested it as I'm a [dircolors ](https://github.com/DHowett/DirColors) user myself.)

Happy to investiate if something's not working.

**Comment by nickcox** [comment]
Closing this. Feel free to reopen if it's still causing you an issue.
