### ISSUE TITLE
`cd` without argument has no function

### ISSUE THREAD

**Issue by thorstenkampe** [nickcox/cd-extras#2]
Traditional Unix shells change to the user's home directory when using `cd` without argument. In its current implementation `cd` just doesn't do anything.

I propose to add functionality:
- change to `$HOME` or
- show the directory stack (like `Pscx` does)
- (something else which gives the user benefit)

**Comment by nickcox** [comment]
Hmm. How would you feel about a `NOARG_CD` setting with a default of `~`?

**Comment by nickcox** [comment]
https://www.powershellgallery.com/packages/cd-extras/0.1.0

**Comment by thorstenkampe** [comment]
`NOARG_CD` would make sense to me

**Comment by nickcox** [comment]
Done. :heavy_check_mark:
