### ISSUE TITLE
CD_PATH expansion does not work with two directories

### ISSUE THREAD

**Issue by jetersen** [nickcox/cd-extras#24]
My guess is that the Windows Terminal consumes the tab character and does not get propagated to cd extra

https://github.com/microsoft/terminal

**Comment by jetersen** [comment]
Okay my issue seems to a mix of Windows Terminal and my profile

For conemu and regular powershell window this works
`$cde.CD_PATH = @($developmentWorkspace)`

For Windows terminal I need
`$cde.CD_PATH = $developmentWorkspace`

`$developmentWorkspace = @("C:\code", "C:\work")`

**Comment by jetersen** [comment]
d0h I had `$cde.CD_PATH = @("$developmentWorkspace")` which was the foobar one
`$cde.CD_PATH = @($developmentWorkspace)` works just fine

**Comment by jetersen** [comment]
Hmm, so for some reason my PowerShell was using 1.1.1

When upgrading to 1.11 CD_PATH no longer works with multiple directories
cc @nickcox

**Comment by nickcox** [comment]
Thanks for this, it's definitely a regression. Should be fixed in [1.12](https://www.powershellgallery.com/packages/cd-extras/1.12).

**Comment by jetersen** [comment]
Thanks @nickcox for the quick response and fix. Massively appreciated 😊
