### ISSUE TITLE
[Suggestion] Mention PSReadLine as a dependency.

### ISSUE THREAD

**Issue by mhidro** [nickcox/cd-extras#27]
For some reason PSReadLine wasn't installed on my machine (win10) but I saw it's required for a bit of the functionality. I quickly fixed that by installing it. 

Maybe you could mention in the readme somewhere that it's required and have a one liner to install the module.

**Comment by nickcox** [comment]
Thanks for the suggestion!

cd-extras *should* work without PSReadLine. What wasn't working, out of interest?

**Comment by nickcox** [comment]
I've added a [link to PSReadLine and described how to check][1] that you've got a `MenuComplete` keybinding at the point where auto-completions are first introduced.

Happy to take a PR if you have any other suggestions. 😄

[1]: https://github.com/nickcox/cd-extras#navigation-helper-completions
