### ISSUE TITLE
Set-Alias : The AllScope option cannot be removed from the alias '~'.

### ISSUE THREAD

**Issue by Mauville** [nickcox/cd-extras#36]
When doing a default installation from the Gallery, I received the previous error after importing the module from my $PROFILE. 
After commenting line 13 of the Aliases.ps1 file, the error goes away, but ~ doesn't work as expected from the module. 

Changing the line from:
https://github.com/nickcox/cd-extras/blob/e111a9edc9f5bf892359a68cd88a508e49ba0683/cd-extras/public/Aliases.ps1#L13

to:
`Set-Alias -Name '~' -Value Undo-Location -Option AllScope`

Seems to solve the problem

**Comment by nickcox** [comment]
Thanks @Mauville.

🧐 wouldn't this only happen if the same alias had already been set with the `AllScope` option? Is it possible you set the alias earlier in your profile? (Or imported a module that sets it?)

**Comment by Mauville** [comment]
Wow. You're absolutely right. Another module I was using defined the same alias. Commenting out the module solved the issue. Sorry for not testing enough before opening an issue 😓
