### ISSUE TITLE
Option to disable beep?

### ISSUE THREAD

**Issue by jetersen** [nickcox/cd-extras#37]
Hi could we have an option to disable the beep?
https://github.com/nickcox/cd-extras/blob/e111a9edc9f5bf892359a68cd88a508e49ba0683/cd-extras/private/CompletePaths.ps1#L120

**Comment by nickcox** [comment]
Yeah, we definitely could.

Out of interest, does it happen often for you? I tend to have a full screen terminal with `$cde.MaxCompletions = 0` and it's pretty rare that I'll max it out.

**Comment by jetersen** [comment]
I rarely use full screen terminal, and dislike any beeping... The terminal should be silent. Who want's to be listening to music and than random beeps coming from your terminal. Honestly the code works as expected, why add the beep? 🤔
I can visually determine when the list has been truncated, I don't need an audio queue.

**Comment by nickcox** [comment]
I was going to suggest adding some sort of visual indicator. 😄

PSReadLine seems to do it with a prompt, `Display all {n} possibilities? (y or n)`, which is also pretty annoying, imo.

**Comment by jetersen** [comment]
If the user does not see the option they are looking for they can finetune the search.

```
Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
```
Seems to provide least annoyance but occasionally it beeps.

**Comment by nickcox** [comment]
What if we made it optionally visible in the custom tooltip section?

![image](https://user-images.githubusercontent.com/135552/115236423-b4f6c100-a15e-11eb-9d11-6b70e2cc96b6.png)

**Comment by jetersen** [comment]
That's way better than a beep 👏

**Comment by nickcox** [comment]
👍

This is sitting in _master_ if you want to try it out. Otherwise I'll likely cut a release in the next week or so.

**Comment by jetersen** [comment]
Tested and works great!

**Comment by jetersen** [comment]
resolved in https://github.com/nickcox/cd-extras/commit/cc803e1e41444a4b1405581f33a7c9df0a9dcb7c
