### ISSUE TITLE
[feature] combine cd+ and cd- as History-Location

### ISSUE THREAD

**Issue by keosu** [nickcox/cd-extras#38]
It is convenient to have history location navigation cmdlet, in many cases, we don't have to distinguish the redo or undo.

**Comment by nickcox** [comment]
Thanks for the suggestion. I've been using this [`Set-RecentLocation`](https://github.com/nickcox/cd-extras/blob/autojump/cd-extras/public/Set-RecentLocation.ps1) cmdlet, alised to `cdr` on a branch for a while.

I have been meaning to move this into master. Would it work for your use case?

**Comment by keosu** [comment]
Yes, definitely. Though I had a imperfect implementation base on your repo, I'll appreciate it if you can merge it into master and push it to powershellgallery soon. I have been using zsh & oh-my-zsh for a long time and I am looking for a similar experience for powershell, you have done a wonderful work, thanks.

**Comment by nickcox** [comment]
This is published as [`3.0.0-beta1`](https://www.powershellgallery.com/packages/cd-extras/3.0.0-beta1). 

You should be able to install it from the gallery with `Update-Module cd-extras -AllowPrerelease`, then navigate recent directories, `cdr`, or frecent directories, `cdf`, with decent autocompletion. Let me know how it goes!

I need to get the docs updated and possibly add some more test cases before I cut a full 3.0 release.

**Comment by keosu** [comment]
Thanks, I tried, at least it works fine for me. 👍
