### ISSUE TITLE
No indication that transpose location failed

### ISSUE THREAD

**Issue by thorstenkampe** [nickcox/cd-extras#5]
Shouldn't there be an error (or at least information) if no transformation could be done? Obviously a user issuing the command expects something to happen:
```
[thorsten] > pwd

Path
----
F:\cygwin\home\thorsten


[thorsten] > cd thorsten guest
[thorsten] > pwd

Path
----
F:\cygwin\home\thorsten
```

**Comment by nickcox** [comment]
Agree. Done in [0.2.0](https://www.powershellgallery.com/packages/cd-extras/0.2.0).
