### ISSUE TITLE
Warning when `#Requires` used

### ISSUE THREAD

**Issue by thorstenkampe** [nickcox/cd-extras#7]
When cd-extras is used in connection with `#Requires -Module cd-extras` a warning issued:
```
WARNING: The names of some imported commands from the module 'cd-extras' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
```
The warning is described in the [Readme](https://github.com/nickcox/cd-extras#install) but since we are not manually importing cd-extras, the workaround is not applicable.

**Comment by nickcox** [comment]
I'm not sure what can be done about this. I guess instead of `#Requires` you could use:
```
If (!(Get-module cd-extras )) {  Import-Module cd-extras -DisableNameChecking }
```
What's the use case? I see _cd-extras_ as a set of tools I'd want to use interactively from the command line more than I would from a script.

**Comment by thorstenkampe** [comment]
I agree. `#Requires` is probably rarely used for one's profile script. I use it as a reminder of the modules I need because I mostly don't explicitly import modules.

On the other hand - what's the use case for not using approved verbs? From what I can see, the recommendation is to use the approved ones and to expose the more fancy verbs to the user as aliases.

Feel free to close this ticket.

**Comment by nickcox** [comment]
In order to use approved verbs, we'd need alternative verbs for:

* Raise
* Transpose
* Peek

I've looked at the list of 'approved' verbs (is it just me or does that sound a bit _1984_?) and I can't find anything more suitable than Set, Set and Get respectively which I think are really weak and undescriptive. I'm pretty sure even Microsoft don't follow these guidelines everywhere (Exchange, SQL Server, etc.) 

Closing for now but open to changing if you think it's important.

**Comment by nickcox** [comment]
On reflection, I think you're right: there's not much downside to using approved verbs combined with aliases. I'm thinking of using:

* `Raise-Location` --> `Step-Up`
* `Transpose-Location` --> ~`Set-TransposedLocation`~ `Switch-LocationPart`
* `Peek-Stack` --> `Show-Stack`

Appreciate any thoughts on these.

**Comment by nickcox** [comment]
https://www.powershellgallery.com/packages/cd-extras/0.5.0
